// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.6
// source: contracts/example.proto

package contracts

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	protos "protos/"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetFeeArguments struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetFeeArguments) Reset() {
	*x = GetFeeArguments{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contracts_example_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFeeArguments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeeArguments) ProtoMessage() {}

func (x *GetFeeArguments) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_example_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeeArguments.ProtoReflect.Descriptor instead.
func (*GetFeeArguments) Descriptor() ([]byte, []int) {
	return file_contracts_example_proto_rawDescGZIP(), []int{0}
}

type GetFeeOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fee *protos.U16 `protobuf:"bytes,1,opt,name=fee,proto3" json:"fee,omitempty"`
}

func (x *GetFeeOutput) Reset() {
	*x = GetFeeOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contracts_example_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFeeOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeeOutput) ProtoMessage() {}

func (x *GetFeeOutput) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_example_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeeOutput.ProtoReflect.Descriptor instead.
func (*GetFeeOutput) Descriptor() ([]byte, []int) {
	return file_contracts_example_proto_rawDescGZIP(), []int{1}
}

func (x *GetFeeOutput) GetFee() *protos.U16 {
	if x != nil {
		return x.Fee
	}
	return nil
}

type DepositArguments struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DepositArguments) Reset() {
	*x = DepositArguments{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contracts_example_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepositArguments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositArguments) ProtoMessage() {}

func (x *DepositArguments) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_example_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositArguments.ProtoReflect.Descriptor instead.
func (*DepositArguments) Descriptor() ([]byte, []int) {
	return file_contracts_example_proto_rawDescGZIP(), []int{2}
}

type DepositOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DepositOutput) Reset() {
	*x = DepositOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contracts_example_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepositOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositOutput) ProtoMessage() {}

func (x *DepositOutput) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_example_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositOutput.ProtoReflect.Descriptor instead.
func (*DepositOutput) Descriptor() ([]byte, []int) {
	return file_contracts_example_proto_rawDescGZIP(), []int{3}
}

type ExchangeArguments struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WithdrawToken *protos.Address `protobuf:"bytes,1,opt,name=withdraw_token,json=withdrawToken,proto3" json:"withdraw_token,omitempty"`
}

func (x *ExchangeArguments) Reset() {
	*x = ExchangeArguments{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contracts_example_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExchangeArguments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeArguments) ProtoMessage() {}

func (x *ExchangeArguments) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_example_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeArguments.ProtoReflect.Descriptor instead.
func (*ExchangeArguments) Descriptor() ([]byte, []int) {
	return file_contracts_example_proto_rawDescGZIP(), []int{4}
}

func (x *ExchangeArguments) GetWithdrawToken() *protos.Address {
	if x != nil {
		return x.WithdrawToken
	}
	return nil
}

type ExchangeOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ExchangeOutput) Reset() {
	*x = ExchangeOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contracts_example_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExchangeOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeOutput) ProtoMessage() {}

func (x *ExchangeOutput) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_example_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeOutput.ProtoReflect.Descriptor instead.
func (*ExchangeOutput) Descriptor() ([]byte, []int) {
	return file_contracts_example_proto_rawDescGZIP(), []int{5}
}

var File_contracts_example_proto protoreflect.FileDescriptor

var file_contracts_example_proto_rawDesc = []byte{
	0x0a, 0x17, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x2f, 0x65, 0x78, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x7a, 0x69, 0x6e, 0x63, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x11, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x46, 0x65, 0x65, 0x41,
	0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x26, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x46,
	0x65, 0x65, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x16, 0x0a, 0x03, 0x66, 0x65, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x04, 0x2e, 0x75, 0x31, 0x36, 0x52, 0x03, 0x66, 0x65, 0x65,
	0x22, 0x12, 0x0a, 0x10, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x41, 0x72, 0x67, 0x75, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x22, 0x0f, 0x0a, 0x0d, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x4f,
	0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x44, 0x0a, 0x11, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x41, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x2f, 0x0a, 0x0e, 0x77, 0x69,
	0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x08, 0x2e, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x0d, 0x77, 0x69,
	0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x10, 0x0a, 0x0e, 0x45,
	0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x42, 0x13, 0x5a,
	0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x73, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_contracts_example_proto_rawDescOnce sync.Once
	file_contracts_example_proto_rawDescData = file_contracts_example_proto_rawDesc
)

func file_contracts_example_proto_rawDescGZIP() []byte {
	file_contracts_example_proto_rawDescOnce.Do(func() {
		file_contracts_example_proto_rawDescData = protoimpl.X.CompressGZIP(file_contracts_example_proto_rawDescData)
	})
	return file_contracts_example_proto_rawDescData
}

var file_contracts_example_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_contracts_example_proto_goTypes = []interface{}{
	(*GetFeeArguments)(nil),   // 0: GetFeeArguments
	(*GetFeeOutput)(nil),      // 1: GetFeeOutput
	(*DepositArguments)(nil),  // 2: DepositArguments
	(*DepositOutput)(nil),     // 3: DepositOutput
	(*ExchangeArguments)(nil), // 4: ExchangeArguments
	(*ExchangeOutput)(nil),    // 5: ExchangeOutput
	(*protos.U16)(nil),        // 6: u16
	(*protos.Address)(nil),    // 7: address
}
var file_contracts_example_proto_depIdxs = []int32{
	6, // 0: GetFeeOutput.fee:type_name -> u16
	7, // 1: ExchangeArguments.withdraw_token:type_name -> address
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_contracts_example_proto_init() }
func file_contracts_example_proto_init() {
	if File_contracts_example_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_contracts_example_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFeeArguments); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contracts_example_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFeeOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contracts_example_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepositArguments); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contracts_example_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepositOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contracts_example_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExchangeArguments); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_contracts_example_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExchangeOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_contracts_example_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_contracts_example_proto_goTypes,
		DependencyIndexes: file_contracts_example_proto_depIdxs,
		MessageInfos:      file_contracts_example_proto_msgTypes,
	}.Build()
	File_contracts_example_proto = out.File
	file_contracts_example_proto_rawDesc = nil
	file_contracts_example_proto_goTypes = nil
	file_contracts_example_proto_depIdxs = nil
}
